/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package DOAN.JAVA.UI;

import javax.swing.JOptionPane;


/**
 *
 * @author TPC
 */
public class frmGiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmGiaoDienChinh
     */
    public frmGiaoDienChinh() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MnKH = new javax.swing.JMenuItem();
        MnNV = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MNKM = new javax.swing.JMenuItem();
        MNCTKM = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MNDMSP = new javax.swing.JMenuItem();
        MNSP = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MNHD = new javax.swing.JMenuItem();
        MNCTHD = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MNNK = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MNXK = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        MNMK = new javax.swing.JMenuItem();
        MNDX = new javax.swing.JMenuItem();
        MNThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 0, 0));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Quản lí");

        jMenu2.setText("1. Quản lí người dùng");

        MnKH.setMnemonic('o');
        MnKH.setText("Quản lí khách hàng");
        MnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnKHActionPerformed(evt);
            }
        });
        jMenu2.add(MnKH);

        MnNV.setText("Quản lí nhân viên");
        MnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNVActionPerformed(evt);
            }
        });
        jMenu2.add(MnNV);

        fileMenu.add(jMenu2);

        jMenu3.setText("2. Quản lí khuyến mãi");

        MNKM.setMnemonic('s');
        MNKM.setText("Quản lí khuyến mãi");
        MNKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNKMActionPerformed(evt);
            }
        });
        jMenu3.add(MNKM);

        MNCTKM.setText("Quản lí chi tiết khuyến mãi");
        MNCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNCTKMActionPerformed(evt);
            }
        });
        jMenu3.add(MNCTKM);

        fileMenu.add(jMenu3);

        jMenu4.setText("3. Quản lí sản phẩm");

        MNDMSP.setText("Quản lí danh mục sản phẩm");
        MNDMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNDMSPActionPerformed(evt);
            }
        });
        jMenu4.add(MNDMSP);

        MNSP.setMnemonic('a');
        MNSP.setText("Quản lí sản phẩm");
        MNSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNSPActionPerformed(evt);
            }
        });
        jMenu4.add(MNSP);

        fileMenu.add(jMenu4);

        jMenu5.setText("4. Quản lí hóa đơn");

        MNHD.setMnemonic('x');
        MNHD.setText("Quản lí hóa đơn");
        MNHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNHDActionPerformed(evt);
            }
        });
        jMenu5.add(MNHD);

        MNCTHD.setText("Quản lí chi tiết hóa đơn");
        MNCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNCTHDActionPerformed(evt);
            }
        });
        jMenu5.add(MNCTHD);

        fileMenu.add(jMenu5);

        jMenu1.setText("5. Quản lí nhập xuất");

        MNNK.setText("Quản lí nhập kho");
        MNNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNNKActionPerformed(evt);
            }
        });
        jMenu1.add(MNNK);

        jMenuItem1.setText("Quản lí chi tiết nhập kho");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MNXK.setText("Quản lí xuất kho");
        MNXK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNXKActionPerformed(evt);
            }
        });
        jMenu1.add(MNXK);

        jMenuItem2.setText("Quản lí chi tiết nhập kho");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        fileMenu.add(jMenu1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Hệ thống");

        MNMK.setMnemonic('t');
        MNMK.setText("Đăng ký tài khoản");
        MNMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNMKActionPerformed(evt);
            }
        });
        editMenu.add(MNMK);

        MNDX.setMnemonic('y');
        MNDX.setText("Đăng xuất");
        MNDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNDXActionPerformed(evt);
            }
        });
        editMenu.add(MNDX);

        MNThoat.setMnemonic('d');
        MNThoat.setText("Thoát");
        MNThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNThoatActionPerformed(evt);
            }
        });
        editMenu.add(MNThoat);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MNHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNHDActionPerformed
        // TODO add your handling code here:
        
        frmQLHoaDon frm7 = new frmQLHoaDon();
        desktopPane.add(frm7);
        frm7.setVisible(true);
        JOptionPane.showMessageDialog(this, "Đang ở trang hóa đơn");
        
   
    }//GEN-LAST:event_MNHDActionPerformed

    private void MNDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNDXActionPerformed
        // TODO add your handling code here:
        
         int option = JOptionPane.showOptionDialog(this, "Bạn có muốn đăng xuất khỏi tài khoản này?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (option == JOptionPane.YES_OPTION) {
            frmDangNhap show = new frmDangNhap();
            show.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_MNDXActionPerformed

    private void MNThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MNThoatActionPerformed

    private void MnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnKHActionPerformed
        // TODO add your handling code here:
        
        frmQLKhachHang frm1 = new frmQLKhachHang();
        desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_MnKHActionPerformed

    private void MnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNVActionPerformed
        // TODO add your handling code here:
        frmQLNhanVien frm2 = new frmQLNhanVien();
        desktopPane.add(frm2);
        frm2.setVisible(true);
    }//GEN-LAST:event_MnNVActionPerformed

    private void MNKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNKMActionPerformed
        // TODO add your handling code here:
        frmQLKhuyenMai frm3 = new frmQLKhuyenMai();
        desktopPane.add(frm3);
        frm3.setVisible(true);  
    }//GEN-LAST:event_MNKMActionPerformed

    private void MNCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNCTKMActionPerformed
        // TODO add your handling code here:
        frmQLCTKhuyenMai frm4 = new frmQLCTKhuyenMai();
        desktopPane.add(frm4);
        frm4.setVisible(true);  
    }//GEN-LAST:event_MNCTKMActionPerformed

    private void MNDMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNDMSPActionPerformed
        // TODO add your handling code here:
        frmQLDMSanPham frm6 = new frmQLDMSanPham();
        desktopPane.add(frm6);
        frm6.setVisible(true);      
    }//GEN-LAST:event_MNDMSPActionPerformed

    private void MNSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNSPActionPerformed
        // TODO add your handling code here:
        frmQLSanPham frm6 = new frmQLSanPham();
        desktopPane.add(frm6);
        frm6.setVisible(true);   
    }//GEN-LAST:event_MNSPActionPerformed

    private void MNCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNCTHDActionPerformed
        // TODO add your handling code here:
        frmQLCTHoaDon frm8 = new frmQLCTHoaDon();
        desktopPane.add(frm8);
        frm8.setVisible(true);  
    }//GEN-LAST:event_MNCTHDActionPerformed

    private void MNNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNNKActionPerformed
        // TODO add your handling code here:
        frmQLNhapKho frm9 = new frmQLNhapKho();
        desktopPane.add(frm9);
        frm9.setVisible(true);   
    }//GEN-LAST:event_MNNKActionPerformed

    private void MNXKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNXKActionPerformed
        // TODO add your handling code here:
        frmQLXuatKho frm = new frmQLXuatKho();
        desktopPane.add(frm);
        frm.setVisible(true);  
    }//GEN-LAST:event_MNXKActionPerformed

    private void MNMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNMKActionPerformed
        // TODO add your handling code here:
        frmDangKyTK frm = new frmDangKyTK();
        desktopPane.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MNMKActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmQLCTNhapKho frm = new frmQLCTNhapKho();
        desktopPane.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmQLCTXuatKho frm = new frmQLCTXuatKho();
        desktopPane.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MNCTHD;
    private javax.swing.JMenuItem MNCTKM;
    private javax.swing.JMenuItem MNDMSP;
    private javax.swing.JMenuItem MNDX;
    private javax.swing.JMenuItem MNHD;
    private javax.swing.JMenuItem MNKM;
    private javax.swing.JMenuItem MNMK;
    private javax.swing.JMenuItem MNNK;
    private javax.swing.JMenuItem MNSP;
    private javax.swing.JMenuItem MNThoat;
    private javax.swing.JMenuItem MNXK;
    private javax.swing.JMenuItem MnKH;
    private javax.swing.JMenuItem MnNV;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
